# Generated by Django 4.2 on 2023-06-06 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='endDate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='register',
            name='startDate',
            field=models.DateField(),
        ),
    ]
