# Generated by Django 4.2 on 2023-06-08 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0003_alter_register_enddate'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='year',
            field=models.IntegerField(default=2000),
            preserve_default=False,
        ),
    ]
