# Generated by Django 4.2 on 2023-06-12 07:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0004_habit_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='publishDate',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
