# Generated by Django 4.2 on 2023-07-01 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0005_register_publishdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='image',
            field=models.URLField(null=True),
        ),
    ]
