# Generated by Django 4.2 on 2023-07-03 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0006_register_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='public',
        ),
        migrations.AddField(
            model_name='register',
            name='year',
            field=models.IntegerField(default=2002),
            preserve_default=False,
        ),
    ]
