# Generated by Django 4.2 on 2023-07-11 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0007_remove_register_public_register_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habit',
            name='type',
        ),
    ]
